timezone:            Europe/Warsaw

markdown:            redcarpet
highlighter:         pygments

permalink:           /:year/:month/:day/:title/
relative_permalinks: true

title:               Konrad's weblog
tagline:             ''
description:         ''
url:                 http://localhost:4000
baseurl:             ''
paginate:            5

author:
  name:              Konrad Zemek
  url:               https://konradzemek.com
  email:             konrad.zemek@gmail.com
