timezone:            Europe/Warsaw

markdown:            redcarpet
highlighter:         pygments
redcarpet:
    extensions:          [footnotes, with_toc_data]

permalink:           /:year/:month/:day/:title/
relative_permalinks: true

title:               Konrad's weblog
tagline:             ''
description:         ''
url:                 https://konradzemek.com
baseurl:             ''
paginate:            5

author:
  name:              Konrad Zemek
  url:               https://konradzemek.com
  email:             konrad.zemek@gmail.com
  linkedin_url:      https://linkedin.com/in/konradzemek
  github_url:        https://github.com/kzemek
